### PR TITLE
Export symbols / Allow calls from other modules

### PR DESCRIPTION
**Pull request by kevin-servaenergy**
Hi. This PR is to export symbols for use in other kernel modules as a softdep. For background, I needed to write a custom module to facilitate dma transfers for a FPGA.

I only exported the symbols that were required for my module.

- Creating and deleting dma buffers as needed
- Retrieving the size of a dma buffer
- Retrieving the 'phys_addr' property

### CODE REVIEW

**Comment by ikwzm** [comment]
Thank you for your pull request.
Please give me a little more time.

**Comment by ikwzm** [comment]
Inspired by your PR, I created a draft version that exports some functions to u-dma-buf for in-kernel. 
It is located in the branch shown below.

https://github.com/ikwzm/udmabuf/tree/in-kernel-develop

I made the following changes to u-dma-buf.c:

 * [add] the following functions for use from in-kernel modules.
      * u_dma_buf_device_search() - Search u-dma-buf device by name or id.
      * u_dma_buf_device_create() - Create u-dma-buf device for in-kernel.
      * u_dma_buf_device_remove() - Remove u-dma-buf device for in-kernel.
      * u_dma_buf_device_getmap() - Get mapping information from u-dma-buf device for in-kernel.
      * u_dma_buf_device_sync()   - Sync for CPU/Device u-dma-buf device for in-kernel.
  * [remove] u-dma-buf-mgr from u-dma-buf.c, because u-dma-buf-gmr is migrated to another kernel module.

**Comment by kevin-servaenergy** [comment]
Awesome! Looks good. Tried out your branch and everything seems to work.

**Comment by ikwzm** [comment]
Thanks for trying.
I'll test it for a while and then release it.

**Comment by ikwzm** [comment]
Thank you for your pull request.
I will close this pull request with thanks to you.

**Pull request closed without merging**
